2020-05-14 07:31:12,110 - accel_code.run - ERROR - could not get subject id from redcap for 827 (2018-10-02 00:00:00)
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/accel/lib/python3.7/site-packages/redcap/project.py", line 57, in configure
    self.metadata = self.__md()
  File "/opt/miniconda-latest/envs/accel/lib/python3.7/site-packages/redcap/project.py", line 93, in __md
    return self._call_api(p_l, 'metadata')[0]
  File "/opt/miniconda-latest/envs/accel/lib/python3.7/site-packages/redcap/project.py", line 155, in _call_api
    return rcr.execute(**request_kwargs)
  File "/opt/miniconda-latest/envs/accel/lib/python3.7/site-packages/redcap/request.py", line 125, in execute
    self.raise_for_status(r)
  File "/opt/miniconda-latest/envs/accel/lib/python3.7/site-packages/redcap/request.py", line 166, in raise_for_status
    r.raise_for_status()
  File "/opt/miniconda-latest/envs/accel/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://redcap.icts.uiowa.edu/redcap/api/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/coder/projects/accel_code/run.py", line 81, in main
    sub_id = redcap_query.redcap_query(lab_id, project, opts.api_key)
  File "/home/coder/projects/accel_code/redcap_query.py", line 14, in redcap_query
    project = redcap.Project(api_url, api_key)
  File "/opt/miniconda-latest/envs/accel/lib/python3.7/site-packages/redcap/project.py", line 53, in __init__
    self.configure()
  File "/opt/miniconda-latest/envs/accel/lib/python3.7/site-packages/redcap/project.py", line 59, in configure
    raise RedcapError("Exporting metadata failed. Check your URL and token.")
requests.exceptions.RequestException: Exporting metadata failed. Check your URL and token.
